/**
 * Client-side PDF renovation quote generator.
 *
 * Builds a professional A4 document from BOM panel data using jsPDF.
 * Design: dark header with amber (#c4915c) accent, clean table layout,
 * category grouping, VAT line, supplier attributions, and Helscoop branding.
 */

import { jsPDF } from "jspdf";
import type { BomItem } from "@/types";
import type { Locale } from "@/lib/i18n";

/* ── i18n strings ─────────────────────────────────────────────── */

const strings = {
  fi: {
    header: "Helscoop \u2014 Kustannusarvio",
    projectName: "Projekti",
    description: "Kuvaus",
    date: "P\u00e4iv\u00e4m\u00e4\u00e4r\u00e4",
    bomTitle: "Materiaalilista",
    colMaterial: "Materiaali",
    colQty: "M\u00e4\u00e4r\u00e4",
    colUnit: "Yks.",
    colUnitPrice: "Yks.hinta",
    colTotal: "Yhteens\u00e4",
    colSupplier: "Toimittaja",
    subtotal: "V\u00c4LISUM.",
    vat: "ALV 25,5 %",
    total: "YHTEENS\u00c4 (sis. ALV)",
    footer: "Luotu Helscoop.fi -palvelulla",
    noDescription: "Ei kuvausta",
    page: "Sivu",
    pricingFrom: "Hintatiedot:",
  },
  en: {
    header: "Helscoop \u2014 Renovation Quote",
    projectName: "Project",
    description: "Description",
    date: "Date",
    bomTitle: "Bill of Materials",
    colMaterial: "Material",
    colQty: "Qty",
    colUnit: "Unit",
    colUnitPrice: "Unit price",
    colTotal: "Total",
    colSupplier: "Supplier",
    subtotal: "SUBTOTAL",
    vat: "VAT 25.5%",
    total: "TOTAL (incl. VAT)",
    footer: "Generated by Helscoop.fi",
    noDescription: "No description",
    page: "Page",
    pricingFrom: "Pricing from:",
  },
} as const;

/* ── colour palette ───────────────────────────────────────────── */

const C = {
  amber: [196, 145, 92] as const,     // #c4915c
  amberLight: [212, 165, 116] as const,
  headerBg: [26, 24, 22] as const,    // #1a1816
  darkText: [26, 24, 22] as const,
  lightText: [224, 220, 212] as const, // #e0dcd4
  mutedText: [138, 133, 125] as const, // #8a857d
  rowAlt: [245, 242, 237] as const,   // #f5f2ed
  tableBorder: [212, 208, 200] as const,
  tableHeaderBg: [61, 56, 49] as const, // #3d3831
  white: [255, 255, 255] as const,
  categoryBg: [235, 231, 224] as const,
};

/* ── Types ────────────────────────────────────────────────────── */

interface PdfOptions {
  projectName: string;
  projectDescription?: string;
  bom: BomItem[];
  locale: Locale;
}

/* ── Helpers ──────────────────────────────────────────────────── */

/** Group BOM items by category_name (fallback "Other"). */
function groupByCategory(bom: BomItem[]): Map<string, BomItem[]> {
  const groups = new Map<string, BomItem[]>();
  for (const item of bom) {
    const cat = item.category_name || "Other";
    const list = groups.get(cat) || [];
    list.push(item);
    groups.set(cat, list);
  }
  return groups;
}

function fmtCurrency(n: number, locale: Locale): string {
  return n.toLocaleString(locale === "fi" ? "fi-FI" : "en-GB", {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function fmtDate(locale: Locale): string {
  return new Date().toLocaleDateString(locale === "fi" ? "fi-FI" : "en-GB", {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

/* ── Main export ──────────────────────────────────────────────── */

export function generateQuotePdf(opts: PdfOptions): void {
  const { projectName, projectDescription, bom, locale } = opts;
  const s = strings[locale];
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();  // 210
  const pageH = doc.internal.pageSize.getHeight(); // 297
  const marginL = 15;
  const marginR = 15;
  const contentW = pageW - marginL - marginR;

  let y = 0; // current vertical position

  /* ── Header band ─────────────────────────────────────────── */

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pageW, 36, "F");

  // Amber accent line below header
  doc.setFillColor(...C.amber);
  doc.rect(0, 36, pageW, 1.2, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...C.lightText);
  doc.text(s.header, marginL, 16);

  // Date right-aligned in header
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.amberLight);
  doc.text(fmtDate(locale), pageW - marginR, 16, { align: "right" });

  // Project name below title
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...C.lightText);
  doc.text(projectName, marginL, 26);

  // Description (truncated)
  if (projectDescription) {
    doc.setFontSize(8);
    doc.setTextColor(...C.mutedText);
    const desc =
      projectDescription.length > 100
        ? projectDescription.substring(0, 100) + "..."
        : projectDescription;
    doc.text(desc, marginL, 32);
  }

  y = 44;

  /* ── BOM table ───────────────────────────────────────────── */

  // Column layout (mm from left margin)
  const cols = {
    material: { x: marginL, w: 62 },
    qty:      { x: marginL + 62, w: 18 },
    unit:     { x: marginL + 80, w: 16 },
    unitPx:   { x: marginL + 96, w: 28 },
    total:    { x: marginL + 124, w: 28 },
    supplier: { x: marginL + 152, w: contentW - 152 + marginL },
  };
  const rowH = 7;
  const headerH = 8;

  function drawTableHeader() {
    // Dark header row
    doc.setFillColor(...C.tableHeaderBg);
    doc.rect(marginL, y, contentW, headerH, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...C.lightText);

    const hY = y + 5.5;
    doc.text(s.colMaterial, cols.material.x + 2, hY);
    doc.text(s.colQty, cols.qty.x + cols.qty.w - 2, hY, { align: "right" });
    doc.text(s.colUnit, cols.unit.x + cols.unit.w - 2, hY, { align: "right" });
    doc.text(s.colUnitPrice, cols.unitPx.x + cols.unitPx.w - 2, hY, { align: "right" });
    doc.text(s.colTotal, cols.total.x + cols.total.w - 2, hY, { align: "right" });
    doc.text(s.colSupplier, cols.supplier.x + 2, hY);

    y += headerH;
  }

  function checkPageBreak(needed: number) {
    if (y + needed > pageH - 25) {
      doc.addPage();
      y = 15;
      drawTableHeader();
    }
  }

  drawTableHeader();

  const categories = groupByCategory(bom);
  let grandTotal = 0;
  let globalRowIdx = 0;

  for (const [categoryName, items] of Array.from(categories)) {
    // Category header row
    checkPageBreak(rowH + rowH); // need room for header + at least one row
    doc.setFillColor(...C.categoryBg);
    doc.rect(marginL, y, contentW, rowH, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(...C.darkText);
    doc.text(categoryName.toUpperCase(), marginL + 2, y + 5);
    y += rowH;

    // Items
    for (const item of items) {
      checkPageBreak(rowH);

      const isAlt = globalRowIdx % 2 === 1;
      if (isAlt) {
        doc.setFillColor(...C.rowAlt);
        doc.rect(marginL, y, contentW, rowH, "F");
      }

      const unitPrice = Number(item.unit_price || 0);
      const lineTotal = Number(item.total || 0);
      grandTotal += lineTotal;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...C.darkText);
      const rY = y + 5;

      // Material name (truncated to fit)
      const matName = (item.material_name || item.material_id || "").substring(0, 40);
      doc.text(matName, cols.material.x + 2, rY);

      // Qty
      doc.text(String(item.quantity), cols.qty.x + cols.qty.w - 2, rY, { align: "right" });

      // Unit
      doc.text(item.unit || "kpl", cols.unit.x + cols.unit.w - 2, rY, { align: "right" });

      // Unit price
      doc.text(fmtCurrency(unitPrice, locale), cols.unitPx.x + cols.unitPx.w - 2, rY, { align: "right" });

      // Line total
      doc.setFont("helvetica", "bold");
      doc.text(fmtCurrency(lineTotal, locale), cols.total.x + cols.total.w - 2, rY, { align: "right" });

      // Supplier
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...C.mutedText);
      doc.text((item.supplier || "").substring(0, 20), cols.supplier.x + 2, rY);

      // Bottom border
      doc.setDrawColor(...C.tableBorder);
      doc.setLineWidth(0.15);
      doc.line(marginL, y + rowH, marginL + contentW, y + rowH);

      y += rowH;
      globalRowIdx++;
    }
  }

  /* ── Totals block ────────────────────────────────────────── */

  checkPageBreak(28);
  y += 3;

  const vatRate = 0.255;
  // The BOM totals already include VAT as stated in the UI ("incl. VAT 25.5%")
  // So we back-calculate the ex-VAT subtotal for the breakdown
  const subtotalExVat = grandTotal / (1 + vatRate);
  const vatAmount = grandTotal - subtotalExVat;

  const totalsX = cols.unitPx.x;

  // Subtotal line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.darkText);
  doc.text(s.subtotal, totalsX - 2, y + 4, { align: "right" });
  doc.text(
    fmtCurrency(subtotalExVat, locale) + " EUR",
    cols.total.x + cols.total.w - 2,
    y + 4,
    { align: "right" }
  );
  y += 6;

  // VAT line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.mutedText);
  doc.text(s.vat, totalsX - 2, y + 4, { align: "right" });
  doc.text(
    fmtCurrency(vatAmount, locale) + " EUR",
    cols.total.x + cols.total.w - 2,
    y + 4,
    { align: "right" }
  );
  y += 7;

  // Grand total row (amber background)
  doc.setFillColor(...C.amber);
  doc.rect(marginL, y, contentW, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...C.white);
  doc.text(s.total, marginL + 4, y + 7);
  doc.text(
    fmtCurrency(grandTotal, locale) + " EUR",
    cols.total.x + cols.total.w - 2,
    y + 7,
    { align: "right" }
  );
  y += 14;

  /* ── Supplier attributions ───────────────────────────────── */

  const suppliers = Array.from(new Set(
    bom
      .map((item) => item.supplier)
      .filter((name): name is string => Boolean(name))
  ));
  if (suppliers.length > 0) {
    checkPageBreak(8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.mutedText);
    doc.text(`${s.pricingFrom} ${suppliers.join(", ")}`, marginL, y + 4);
    y += 8;
  }

  /* ── Footer on every page ────────────────────────────────── */

  const pageCount = doc.getNumberOfPages();
  const timestamp = new Date().toISOString().replace("T", " ").substring(0, 19);

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.mutedText);

    // Left: branding + timestamp
    doc.text(`${s.footer} \u2014 ${timestamp}`, marginL, pageH - 8);

    // Right: page number
    doc.text(`${s.page} ${i} / ${pageCount}`, pageW - marginR, pageH - 8, {
      align: "right",
    });

    // Amber rule above footer
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.3);
    doc.line(marginL, pageH - 12, pageW - marginR, pageH - 12);
  }

  /* ── Trigger download ────────────────────────────────────── */

  const safeName = projectName.replace(/[^a-zA-Z0-9_\- ]/g, "_").replace(/\s+/g, "_");
  doc.save(`helscoop_${safeName}.pdf`);
}
