/**
 * Client-side PDF renovation quote generator.
 *
 * Builds a professional A4 document from BOM panel data using jsPDF.
 * Design: dark header with amber (#c4915c) accent, clean table layout,
 * category grouping, VAT line, supplier attributions, and Helscoop branding.
 */

import { jsPDF } from "jspdf";
import type { BomItem, BuildingInfo } from "@/types";
import type { Locale } from "@/lib/i18n";
import { calculateHouseholdDeduction, type HouseholdDeductionRow } from "@/lib/household-deduction";

/* ── i18n strings ─────────────────────────────────────────────── */

const strings = {
  fi: {
    header: "Helscoop \u2014 Kustannusarvio",
    projectName: "Projekti",
    description: "Kuvaus",
    date: "P\u00e4iv\u00e4m\u00e4\u00e4r\u00e4",
    bomTitle: "Materiaalilista",
    colMaterial: "Materiaali",
    colQty: "M\u00e4\u00e4r\u00e4",
    colUnit: "Yks.",
    colUnitPrice: "Yks.hinta",
    colTotal: "Yhteens\u00e4",
    colSupplier: "Toimittaja",
    subtotal: "V\u00c4LISUM.",
    vat: "ALV 25,5 %",
    total: "YHTEENS\u00c4 (sis. ALV)",
    footer: "Luotu Helscoop.fi -palvelulla",
    noDescription: "Ei kuvausta",
    page: "Sivu",
    pricingFrom: "Hintatiedot:",
  },
  en: {
    header: "Helscoop \u2014 Renovation Quote",
    projectName: "Project",
    description: "Description",
    date: "Date",
    bomTitle: "Bill of Materials",
    colMaterial: "Material",
    colQty: "Qty",
    colUnit: "Unit",
    colUnitPrice: "Unit price",
    colTotal: "Total",
    colSupplier: "Supplier",
    subtotal: "SUBTOTAL",
    vat: "VAT 25.5%",
    total: "TOTAL (incl. VAT)",
    footer: "Generated by Helscoop.fi",
    noDescription: "No description",
    page: "Page",
    pricingFrom: "Pricing from:",
  },
  sv: {
    header: "Helscoop \u2014 Renoveringsoffert",
    projectName: "Projekt",
    description: "Beskrivning",
    date: "Datum",
    bomTitle: "Materiallista",
    colMaterial: "Material",
    colQty: "Antal",
    colUnit: "Enhet",
    colUnitPrice: "Enhetspris",
    colTotal: "Totalt",
    colSupplier: "Leverant\u00f6r",
    subtotal: "DELSUMMA",
    vat: "Moms 25,5 %",
    total: "TOTALT (inkl. moms)",
    footer: "Genererad av Helscoop.fi",
    noDescription: "Ingen beskrivning",
    page: "Sida",
    pricingFrom: "Priser fr\u00e5n:",
  },
} as const;

/* ── colour palette ───────────────────────────────────────────── */

const C = {
  amber: [196, 145, 92] as const,     // #c4915c
  amberLight: [212, 165, 116] as const,
  headerBg: [26, 24, 22] as const,    // #1a1816
  darkText: [26, 24, 22] as const,
  lightText: [224, 220, 212] as const, // #e0dcd4
  mutedText: [138, 133, 125] as const, // #8a857d
  rowAlt: [245, 242, 237] as const,   // #f5f2ed
  tableBorder: [212, 208, 200] as const,
  tableHeaderBg: [61, 56, 49] as const, // #3d3831
  white: [255, 255, 255] as const,
  categoryBg: [235, 231, 224] as const,
};

/* ── Types ────────────────────────────────────────────────────── */

interface PdfOptions {
  projectName: string;
  projectDescription?: string;
  bom: BomItem[];
  locale: Locale;
}

interface AraGrantPdfOptions extends PdfOptions {
  buildingInfo?: BuildingInfo | null;
  sceneJs?: string;
  sceneImage?: string | null;
  manualChecklist?: string[];
}

interface ProposalPdfOptions extends PdfOptions {
  buildingInfo?: BuildingInfo | null;
  sceneJs?: string;
  sceneImage?: string | null;
  beforeImage?: string | null;
  householdDeductionJoint?: boolean;
}

type EnergyClass = "A" | "B" | "C" | "D" | "E" | "F" | "G";

const ENERGY_CLASSES: EnergyClass[] = ["A", "B", "C", "D", "E", "F", "G"];

const araStrings = {
  fi: {
    header: "Helscoop — ARA energia-avustuspaketti",
    subtitle: "Hakemuksen liitepaketti ennen työn aloitusta",
    project: "Projekti",
    date: "Päivämäärä",
    building: "Rakennuksen lähtötiedot",
    plan: "Remonttisuunnitelma",
    plannedView: "Suunniteltu 3D-näkymä",
    noView: "3D-kuvaa ei ollut saatavilla vientihetkellä.",
    energy: "Energialuokka ennen / jälkeen",
    before: "Ennen",
    after: "Jälkeen",
    basis: "Arvion peruste",
    cost: "Kustannusarvio",
    attachments: "ARA-liitteet, jotka omistajan pitää lisätä käsin",
    materialSpec: "Materiaalierittely",
    disclaimer: "Alustava Helscoop-arvio. Varmista luvut virallisella energiatodistuksella ja ARA:n ajantasaisilla ohjeilla ennen hakemusta.",
    sceneObjects: "Scene-objektit",
    sceneLines: "Scene-rivit",
    colMaterial: "Materiaali",
    colQty: "Määrä",
    colUnit: "Yks.",
    colPrice: "Hinta",
    total: "Yhteensä",
    footer: "Luotu Helscoop.fi-palvelulla",
  },
  en: {
    header: "Helscoop — ARA Energy Grant Package",
    subtitle: "Application attachment pack before work starts",
    project: "Project",
    date: "Date",
    building: "Building baseline",
    plan: "Renovation plan",
    plannedView: "Planned 3D view",
    noView: "3D snapshot was not available at export time.",
    energy: "Energy class before / after",
    before: "Before",
    after: "After",
    basis: "Estimate basis",
    cost: "Cost estimate",
    attachments: "ARA attachments the owner must add manually",
    materialSpec: "Material specification",
    disclaimer: "Preliminary Helscoop estimate. Verify figures with an official energy certificate and current ARA instructions before submission.",
    sceneObjects: "Scene objects",
    sceneLines: "Scene lines",
    colMaterial: "Material",
    colQty: "Qty",
    colUnit: "Unit",
    colPrice: "Price",
    total: "Total",
    footer: "Generated by Helscoop.fi",
  },
  sv: {
    header: "Helscoop \u2014 ARA Energibidragspaket",
    subtitle: "Ans\u00f6kningsbilaga innan arbetet p\u00e5b\u00f6rjas",
    project: "Projekt",
    date: "Datum",
    building: "Byggnadsutg\u00e5ngspunkt",
    plan: "Renoveringsplan",
    plannedView: "Planerad 3D-vy",
    noView: "3D-bild var inte tillg\u00e4nglig vid exporttillf\u00e4llet.",
    energy: "Energiklass f\u00f6re / efter",
    before: "F\u00f6re",
    after: "Efter",
    basis: "Uppskattningsgrund",
    cost: "Kostnadsuppskattning",
    attachments: "ARA-bilagor som \u00e4garen m\u00e5ste l\u00e4gga till manuellt",
    materialSpec: "Materialspecifikation",
    disclaimer: "Prelimin\u00e4r Helscoop-uppskattning. Verifiera siffrorna med ett officiellt energicertifikat och aktuella ARA-instruktioner f\u00f6re ans\u00f6kan.",
    sceneObjects: "Scenobjekt",
    sceneLines: "Scenrader",
    colMaterial: "Material",
    colQty: "Antal",
    colUnit: "Enhet",
    colPrice: "Pris",
    total: "Totalt",
    footer: "Genererad av Helscoop.fi",
  },
} as const;

const proposalStrings = {
  fi: {
    header: "Helscoop — remonttiehdotus",
    subtitle: "Asiakas- ja urakoitsijakäyttöön koottu projektipaketti",
    coverLabel: "Projektiehdotus",
    prepared: "Luotu",
    overview: "Rakennuksen yleiskuva",
    visuals: "Ennen / jälkeen näkymät",
    before: "Nykytila",
    after: "Suunnitelma",
    noImage: "Näkymää ei ollut saatavilla vientihetkellä.",
    scope: "Remontin laajuus",
    scopeIntro: "Suunnitelma perustuu projektin materiaalilistaan ja 3D-malliin.",
    bom: "Materiaalierittely",
    cost: "Kustannusyhteenveto",
    total: "Arvio yhteensä",
    labourBasis: "Arvioitu työn osuus",
    householdCredit: "Kotitalousvähennysarvio",
    netCost: "Nettokustannus vähennyksen jälkeen",
    timeline: "Ehdotettu eteneminen",
    footer: "Luotu Helscoop.fi-palvelulla",
    address: "Osoite",
    year: "Rakennusvuosi",
    area: "Pinta-ala",
    type: "Tyyppi",
    heating: "Lämmitys",
    rows: "riviä",
    disclaimer: "Alustava suunnitteluasiakirja. Varmista mitat, luvat, työosuus ja hinnat urakoitsijalta ennen tilausta.",
  },
  en: {
    header: "Helscoop — Renovation Proposal",
    subtitle: "Client and contractor-facing project pack",
    coverLabel: "Project proposal",
    prepared: "Prepared",
    overview: "Building overview",
    visuals: "Before / after views",
    before: "Current state",
    after: "Planned state",
    noImage: "View was not available at export time.",
    scope: "Renovation scope",
    scopeIntro: "The proposal is based on the project BOM and 3D model.",
    bom: "Material specification",
    cost: "Cost summary",
    total: "Estimated total",
    labourBasis: "Estimated labour basis",
    householdCredit: "Household deduction estimate",
    netCost: "Net cost after deduction",
    timeline: "Suggested sequence",
    footer: "Generated by Helscoop.fi",
    address: "Address",
    year: "Year built",
    area: "Area",
    type: "Type",
    heating: "Heating",
    rows: "rows",
    disclaimer: "Preliminary planning document. Verify dimensions, permits, labour split, and prices with contractors before ordering.",
  },
  sv: {
    header: "Helscoop — Renoveringsförslag",
    subtitle: "Projektpaket för kund och entreprenör",
    coverLabel: "Projektförslag",
    prepared: "Skapat",
    overview: "Byggnadsöversikt",
    visuals: "Före / efter vyer",
    before: "Nuläge",
    after: "Planerat läge",
    noImage: "Vyn var inte tillgänglig vid exporttillfället.",
    scope: "Renoveringens omfattning",
    scopeIntro: "Förslaget baseras på projektets materiallista och 3D-modell.",
    bom: "Materialspecifikation",
    cost: "Kostnadssammanfattning",
    total: "Uppskattad total",
    labourBasis: "Uppskattad arbetsandel",
    householdCredit: "Uppskattat hushållsavdrag",
    netCost: "Nettokostnad efter avdrag",
    timeline: "Föreslagen ordning",
    footer: "Genererad av Helscoop.fi",
    address: "Adress",
    year: "Byggår",
    area: "Yta",
    type: "Typ",
    heating: "Uppvärmning",
    rows: "rader",
    disclaimer: "Preliminärt planeringsdokument. Verifiera mått, tillstånd, arbetsandel och priser med entreprenörer före beställning.",
  },
} as const;

/* ── Helpers ──────────────────────────────────────────────────── */

/** Group BOM items by category_name (fallback "Other"). */
function groupByCategory(bom: BomItem[]): Map<string, BomItem[]> {
  const groups = new Map<string, BomItem[]>();
  for (const item of bom) {
    const cat = item.category_name || "Other";
    const list = groups.get(cat) || [];
    list.push(item);
    groups.set(cat, list);
  }
  return groups;
}

function localeTag(locale: Locale): string {
  if (locale === "fi") return "fi-FI";
  if (locale === "sv") return "sv-SE";
  return "en-GB";
}

function fmtCurrency(n: number, locale: Locale): string {
  return n.toLocaleString(localeTag(locale), {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  });
}

function fmtDate(locale: Locale): string {
  return new Date().toLocaleDateString(localeTag(locale), {
    year: "numeric",
    month: "long",
    day: "numeric",
  });
}

function safeFilePart(value: string): string {
  return value.replace(/[^a-zA-Z0-9_\- ]/g, "_").replace(/\s+/g, "_");
}

function bomText(bom: BomItem[]): string {
  return bom
    .map((item) =>
      [
        item.material_id,
        item.material_name,
        item.category_name,
      ].filter(Boolean).join(" ")
    )
    .join(" ")
    .toLowerCase();
}

function classIndexFromBuilding(buildingInfo?: BuildingInfo | null): number {
  const year = buildingInfo?.year_built ?? 1985;
  let idx = 4; // E by default for older Finnish detached stock.

  if (year >= 2018) idx = 1;
  else if (year >= 2010) idx = 2;
  else if (year >= 1990) idx = 3;
  else if (year >= 1970) idx = 4;
  else idx = 5;

  const heating = buildingInfo?.heating?.toLowerCase() ?? "";
  if (heating.includes("maalampo") || heating.includes("maalämpö")) idx -= 1;
  if (heating.includes("oljy") || heating.includes("öljy") || heating.includes("sahko") || heating.includes("sähkö")) idx += 1;

  return Math.max(0, Math.min(ENERGY_CLASSES.length - 1, idx));
}

function projectedClassIndex(currentIdx: number, bom: BomItem[]): { idx: number; reasons: string[] } {
  const text = bomText(bom);
  const total = bom.reduce((sum, item) => sum + Number(item.total || 0), 0);
  let improvement = 0;
  const reasons: string[] = [];

  if (/insulation|eriste|villa|mineraalivilla|puukuitu/.test(text)) {
    improvement += 1;
    reasons.push("insulation scope");
  }
  if (/window|ikkuna|triple|kolmilasi/.test(text)) {
    improvement += 1;
    reasons.push("window upgrade scope");
  }
  if (/heat pump|lämpöpumppu|lampopumppu|maalampo|maalämpö/.test(text)) {
    improvement += 2;
    reasons.push("heat-pump/heating-system scope");
  }
  if (/roof|katto|yläpohja|ylapohja/.test(text) && /insulation|eriste|villa/.test(text)) {
    improvement += 1;
    reasons.push("roof insulation scope");
  }
  if (total >= 20000) {
    improvement += 1;
    reasons.push("major renovation budget");
  }

  return {
    idx: Math.max(0, currentIdx - Math.min(3, improvement)),
    reasons: reasons.length > 0 ? reasons : ["no energy-improving BOM scope detected"],
  };
}

function sceneStats(sceneJs?: string): { lines: number; objects: number } {
  const script = sceneJs ?? "";
  return {
    lines: script ? script.split("\n").length : 0,
    objects: (script.match(/scene\.add\(/g) ?? []).length,
  };
}

function defaultAraChecklist(locale: Locale): string[] {
  if (locale === "fi") {
    return [
      "Omistusoikeuden todistus tai taloyhtiön päätös",
      "Henkilö-/Y-tunnus ja hakijan yhteystiedot",
      "Virallinen energiatodistus tai energiaselvitys",
      "Urakoitsijan tarjoukset ja aikataulu",
      "Tarvittavat rakennus- tai toimenpideluvat",
      "Valokuvat nykytilanteesta ennen työn aloitusta",
    ];
  }
  return [
    "Proof of ownership or housing-company decision",
    "Applicant tax ID and contact details",
    "Official energy certificate or energy report",
    "Contractor quotes and schedule",
    "Required building/action permits",
    "Before-work photos of current conditions",
  ];
}

function addFooter(doc: jsPDF, locale: Locale, pageW: number, pageH: number, marginL: number, marginR: number): void {
  const s = araStrings[locale];
  const pageCount = doc.getNumberOfPages();
  const timestamp = new Date().toISOString().replace("T", " ").substring(0, 19);

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.mutedText);
    doc.text(`${s.footer} — ${timestamp}`, marginL, pageH - 8);
    doc.text(`${strings[locale].page} ${i} / ${pageCount}`, pageW - marginR, pageH - 8, {
      align: "right",
    });
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.3);
    doc.line(marginL, pageH - 12, pageW - marginR, pageH - 12);
  }
}

/* ── Main export ──────────────────────────────────────────────── */

export function generateQuotePdf(opts: PdfOptions): void {
  const { projectName, projectDescription, bom, locale } = opts;
  const s = strings[locale];
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });

  const pageW = doc.internal.pageSize.getWidth();  // 210
  const pageH = doc.internal.pageSize.getHeight(); // 297
  const marginL = 15;
  const marginR = 15;
  const contentW = pageW - marginL - marginR;

  let y = 0; // current vertical position

  /* ── Header band ─────────────────────────────────────────── */

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pageW, 36, "F");

  // Amber accent line below header
  doc.setFillColor(...C.amber);
  doc.rect(0, 36, pageW, 1.2, "F");

  // Title
  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.setTextColor(...C.lightText);
  doc.text(s.header, marginL, 16);

  // Date right-aligned in header
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.amberLight);
  doc.text(fmtDate(locale), pageW - marginR, 16, { align: "right" });

  // Project name below title
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);
  doc.setTextColor(...C.lightText);
  doc.text(projectName, marginL, 26);

  // Description (truncated)
  if (projectDescription) {
    doc.setFontSize(8);
    doc.setTextColor(...C.mutedText);
    const desc =
      projectDescription.length > 100
        ? projectDescription.substring(0, 100) + "..."
        : projectDescription;
    doc.text(desc, marginL, 32);
  }

  y = 44;

  /* ── BOM table ───────────────────────────────────────────── */

  // Column layout (mm from left margin)
  const cols = {
    material: { x: marginL, w: 62 },
    qty:      { x: marginL + 62, w: 18 },
    unit:     { x: marginL + 80, w: 16 },
    unitPx:   { x: marginL + 96, w: 28 },
    total:    { x: marginL + 124, w: 28 },
    supplier: { x: marginL + 152, w: contentW - 152 + marginL },
  };
  const rowH = 7;
  const headerH = 8;

  function drawTableHeader() {
    // Dark header row
    doc.setFillColor(...C.tableHeaderBg);
    doc.rect(marginL, y, contentW, headerH, "F");

    doc.setFont("helvetica", "bold");
    doc.setFontSize(7);
    doc.setTextColor(...C.lightText);

    const hY = y + 5.5;
    doc.text(s.colMaterial, cols.material.x + 2, hY);
    doc.text(s.colQty, cols.qty.x + cols.qty.w - 2, hY, { align: "right" });
    doc.text(s.colUnit, cols.unit.x + cols.unit.w - 2, hY, { align: "right" });
    doc.text(s.colUnitPrice, cols.unitPx.x + cols.unitPx.w - 2, hY, { align: "right" });
    doc.text(s.colTotal, cols.total.x + cols.total.w - 2, hY, { align: "right" });
    doc.text(s.colSupplier, cols.supplier.x + 2, hY);

    y += headerH;
  }

  function checkPageBreak(needed: number) {
    if (y + needed > pageH - 25) {
      doc.addPage();
      y = 15;
      drawTableHeader();
    }
  }

  drawTableHeader();

  const categories = groupByCategory(bom);
  let grandTotal = 0;
  let globalRowIdx = 0;

  for (const [categoryName, items] of Array.from(categories)) {
    // Category header row
    checkPageBreak(rowH + rowH); // need room for header + at least one row
    doc.setFillColor(...C.categoryBg);
    doc.rect(marginL, y, contentW, rowH, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(7.5);
    doc.setTextColor(...C.darkText);
    doc.text(categoryName.toUpperCase(), marginL + 2, y + 5);
    y += rowH;

    // Items
    for (const item of items) {
      checkPageBreak(rowH);

      const isAlt = globalRowIdx % 2 === 1;
      if (isAlt) {
        doc.setFillColor(...C.rowAlt);
        doc.rect(marginL, y, contentW, rowH, "F");
      }

      const unitPrice = Number(item.unit_price || 0);
      const lineTotal = Number(item.total || 0);
      grandTotal += lineTotal;

      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...C.darkText);
      const rY = y + 5;

      // Material name (truncated to fit)
      const matName = (item.material_name || item.material_id || "").substring(0, 40);
      doc.text(matName, cols.material.x + 2, rY);

      // Qty
      doc.text(String(item.quantity), cols.qty.x + cols.qty.w - 2, rY, { align: "right" });

      // Unit
      doc.text(item.unit || "kpl", cols.unit.x + cols.unit.w - 2, rY, { align: "right" });

      // Unit price
      doc.text(fmtCurrency(unitPrice, locale), cols.unitPx.x + cols.unitPx.w - 2, rY, { align: "right" });

      // Line total
      doc.setFont("helvetica", "bold");
      doc.text(fmtCurrency(lineTotal, locale), cols.total.x + cols.total.w - 2, rY, { align: "right" });

      // Supplier
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7);
      doc.setTextColor(...C.mutedText);
      doc.text((item.supplier || "").substring(0, 20), cols.supplier.x + 2, rY);

      // Bottom border
      doc.setDrawColor(...C.tableBorder);
      doc.setLineWidth(0.15);
      doc.line(marginL, y + rowH, marginL + contentW, y + rowH);

      y += rowH;
      globalRowIdx++;
    }
  }

  /* ── Totals block ────────────────────────────────────────── */

  checkPageBreak(28);
  y += 3;

  const vatRate = 0.255;
  // The BOM totals already include VAT as stated in the UI ("incl. VAT 25.5%")
  // So we back-calculate the ex-VAT subtotal for the breakdown
  const subtotalExVat = grandTotal / (1 + vatRate);
  const vatAmount = grandTotal - subtotalExVat;

  const totalsX = cols.unitPx.x;

  // Subtotal line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.darkText);
  doc.text(s.subtotal, totalsX - 2, y + 4, { align: "right" });
  doc.text(
    fmtCurrency(subtotalExVat, locale) + " EUR",
    cols.total.x + cols.total.w - 2,
    y + 4,
    { align: "right" }
  );
  y += 6;

  // VAT line
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.mutedText);
  doc.text(s.vat, totalsX - 2, y + 4, { align: "right" });
  doc.text(
    fmtCurrency(vatAmount, locale) + " EUR",
    cols.total.x + cols.total.w - 2,
    y + 4,
    { align: "right" }
  );
  y += 7;

  // Grand total row (amber background)
  doc.setFillColor(...C.amber);
  doc.rect(marginL, y, contentW, 10, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(11);
  doc.setTextColor(...C.white);
  doc.text(s.total, marginL + 4, y + 7);
  doc.text(
    fmtCurrency(grandTotal, locale) + " EUR",
    cols.total.x + cols.total.w - 2,
    y + 7,
    { align: "right" }
  );
  y += 14;

  /* ── Supplier attributions ───────────────────────────────── */

  const suppliers = Array.from(new Set(
    bom
      .map((item) => item.supplier)
      .filter((name): name is string => Boolean(name))
  ));
  if (suppliers.length > 0) {
    checkPageBreak(8);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.mutedText);
    doc.text(`${s.pricingFrom} ${suppliers.join(", ")}`, marginL, y + 4);
    y += 8;
  }

  /* ── Footer on every page ────────────────────────────────── */

  const pageCount = doc.getNumberOfPages();
  const timestamp = new Date().toISOString().replace("T", " ").substring(0, 19);

  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.mutedText);

    // Left: branding + timestamp
    doc.text(`${s.footer} \u2014 ${timestamp}`, marginL, pageH - 8);

    // Right: page number
    doc.text(`${s.page} ${i} / ${pageCount}`, pageW - marginR, pageH - 8, {
      align: "right",
    });

    // Amber rule above footer
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.3);
    doc.line(marginL, pageH - 12, pageW - marginR, pageH - 12);
  }

  /* ── Trigger download ────────────────────────────────────── */

  const safeName = projectName.replace(/[^a-zA-Z0-9_\- ]/g, "_").replace(/\s+/g, "_");
  doc.save(`helscoop_${safeName}.pdf`);
}

export function generateProposalPdf(opts: ProposalPdfOptions): void {
  const {
    projectName,
    projectDescription,
    bom,
    locale,
    buildingInfo,
    sceneJs,
    sceneImage,
    beforeImage,
    householdDeductionJoint,
  } = opts;
  const s = proposalStrings[locale];
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginL = 15;
  const marginR = 15;
  const contentW = pageW - marginL - marginR;
  const grandTotal = bom.reduce((sum, item) => sum + Number(item.total || 0), 0);
  const labourBasis = Math.round(grandTotal * 0.45 * 100) / 100;
  const deductionRows: HouseholdDeductionRow[] = [
    { type: "material", label: "Materials", amount: Math.max(0, grandTotal - labourBasis) },
    { type: "labour", label: "Labour", amount: labourBasis },
  ];
  const deduction = calculateHouseholdDeduction(deductionRows, { coupleMode: householdDeductionJoint });
  const stats = sceneStats(sceneJs);
  const categories = Array.from(groupByCategory(bom));
  let y = 0;

  const ensure = (needed: number) => {
    if (y + needed > pageH - 24) {
      doc.addPage();
      y = 18;
    }
  };

  const section = (title: string) => {
    ensure(16);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...C.darkText);
    doc.text(title, marginL, y);
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.5);
    doc.line(marginL, y + 2, pageW - marginR, y + 2);
    y += 9;
  };

  const paragraph = (text: string, x: number, maxW: number, lineH = 5) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...C.darkText);
    const lines = doc.splitTextToSize(text, maxW);
    doc.text(lines, x, y);
    y += lines.length * lineH;
  };

  const drawImageBox = (image: string | null | undefined, x: number, top: number, w: number, h: number, label: string) => {
    doc.setFillColor(...C.rowAlt);
    doc.rect(x, top, w, h, "F");
    doc.setDrawColor(...C.tableBorder);
    doc.rect(x, top, w, h);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...C.darkText);
    doc.text(label, x + 3, top + 6);
    if (image) {
      try {
        const format = image.startsWith("data:image/jpeg") || image.startsWith("data:image/jpg") ? "JPEG" : "PNG";
        doc.addImage(image, format, x + 3, top + 10, w - 6, h - 15, undefined, "FAST");
        return;
      } catch {
        // Fall through to placeholder; user still receives the full proposal.
      }
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...C.mutedText);
    doc.text(s.noImage, x + 3, top + h / 2, { maxWidth: w - 6 });
  };

  const keyValue = (label: string, value: string | number | undefined | null) => {
    if (value == null || value === "") return;
    ensure(7);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...C.mutedText);
    doc.text(label, marginL, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(...C.darkText);
    doc.text(String(value), marginL + 42, y, { maxWidth: contentW - 42 });
    y += 6;
  };

  const scopeLines = categories.slice(0, 5).map(([category, items]) => {
    const total = items.reduce((sum, item) => sum + Number(item.total || 0), 0);
    return `${category}: ${items.length} ${s.rows}, ${fmtCurrency(total, locale)} EUR`;
  });

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pageW, 62, "F");
  doc.setFillColor(...C.amber);
  doc.rect(0, 62, pageW, 1.2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(19);
  doc.setTextColor(...C.lightText);
  doc.text(s.header, marginL, 17);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.amberLight);
  doc.text(s.subtitle, marginL, 27);
  doc.text(fmtDate(locale), pageW - marginR, 17, { align: "right" });
  doc.setFont("helvetica", "bold");
  doc.setFontSize(15);
  doc.setTextColor(...C.white);
  doc.text(projectName, marginL, 43, { maxWidth: 132 });
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.lightText);
  doc.text(`${s.coverLabel} · ${s.prepared} ${fmtDate(locale)}`, marginL, 53);

  y = 74;
  if (sceneImage) {
    drawImageBox(sceneImage, marginL, y, contentW, 78, s.after);
    y += 88;
  }

  section(s.overview);
  keyValue(s.address, buildingInfo?.address);
  keyValue(s.type, buildingInfo?.type);
  keyValue(s.year, buildingInfo?.year_built);
  keyValue(s.area, buildingInfo?.area_m2 ? `${buildingInfo.area_m2} m²` : undefined);
  keyValue(s.heating, buildingInfo?.heating);
  keyValue(strings[locale].description, projectDescription || strings[locale].noDescription);
  keyValue("3D", `${stats.objects} objects / ${stats.lines} lines`);

  doc.addPage();
  y = 18;
  section(s.visuals);
  const imageW = (contentW - 6) / 2;
  drawImageBox(beforeImage, marginL, y, imageW, 72, s.before);
  drawImageBox(sceneImage, marginL + imageW + 6, y, imageW, 72, s.after);
  y += 82;

  section(s.scope);
  paragraph(s.scopeIntro, marginL, contentW);
  y += 2;
  for (const line of scopeLines) {
    ensure(6);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.setTextColor(...C.darkText);
    doc.text(`• ${line}`, marginL + 3, y);
    y += 5;
  }

  section(s.cost);
  const costRows = [
    [s.total, `${fmtCurrency(grandTotal, locale)} EUR`],
    [s.labourBasis, `${fmtCurrency(labourBasis, locale)} EUR`],
    [s.householdCredit, `${fmtCurrency(deduction.credit, locale)} EUR`],
    [s.netCost, `${fmtCurrency(deduction.netCost, locale)} EUR`],
  ];
  for (const [label, value] of costRows) {
    ensure(9);
    doc.setFillColor(label === s.netCost ? C.categoryBg[0] : C.white[0], label === s.netCost ? C.categoryBg[1] : C.white[1], label === s.netCost ? C.categoryBg[2] : C.white[2]);
    doc.rect(marginL, y - 4, contentW, 8, "F");
    doc.setFont("helvetica", label === s.netCost ? "bold" : "normal");
    doc.setFontSize(9);
    doc.setTextColor(...C.darkText);
    doc.text(label, marginL + 3, y + 1);
    doc.text(value, pageW - marginR - 3, y + 1, { align: "right" });
    y += 8;
  }

  section(s.timeline);
  const timeline = locale === "fi"
    ? ["1. Tarkista mitat ja lupatarve", "2. Lähetä paketti 2–3 urakoitsijalle", "3. Varmista työosuus ja aikataulu", "4. Tilaa materiaalit ja sovi aloitus"]
    : locale === "sv"
      ? ["1. Kontrollera mått och tillståndsbehov", "2. Skicka paketet till 2–3 entreprenörer", "3. Bekräfta arbetsandel och tidtabell", "4. Beställ material och boka start"]
      : ["1. Verify dimensions and permit need", "2. Send this pack to 2–3 contractors", "3. Confirm labour split and schedule", "4. Order materials and agree start date"];
  for (const line of timeline) {
    ensure(6);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);
    doc.text(line, marginL + 3, y);
    y += 6;
  }

  doc.addPage();
  y = 18;
  section(s.bom);
  for (const [category, items] of categories) {
    ensure(11);
    doc.setFillColor(...C.categoryBg);
    doc.rect(marginL, y - 4, contentW, 7, "F");
    doc.setFont("helvetica", "bold");
    doc.setFontSize(8);
    doc.setTextColor(...C.darkText);
    doc.text(category.toUpperCase(), marginL + 2, y + 1);
    y += 7;

    for (const item of items.slice(0, 36)) {
      ensure(6);
      const lineTotal = Number(item.total || 0);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.setTextColor(...C.darkText);
      doc.text((item.material_name || item.material_id).slice(0, 72), marginL + 2, y);
      doc.text(`${item.quantity} ${item.unit || ""}`, marginL + 95, y, { align: "right" });
      doc.text(`${fmtCurrency(lineTotal, locale)} EUR`, pageW - marginR - 2, y, { align: "right" });
      y += 5;
    }
  }

  ensure(16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...C.mutedText);
  doc.text(s.disclaimer, marginL, y + 4, { maxWidth: contentW });

  const pageCount = doc.getNumberOfPages();
  const timestamp = new Date().toISOString().replace("T", " ").substring(0, 19);
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7);
    doc.setTextColor(...C.mutedText);
    doc.text(`${s.footer} — ${timestamp}`, marginL, pageH - 8);
    doc.text(`${strings[locale].page} ${i} / ${pageCount}`, pageW - marginR, pageH - 8, { align: "right" });
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.3);
    doc.line(marginL, pageH - 12, pageW - marginR, pageH - 12);
  }

  doc.save(`helscoop_proposal_${safeFilePart(projectName)}.pdf`);
}

export function generateAraGrantPdf(opts: AraGrantPdfOptions): void {
  const {
    projectName,
    projectDescription,
    bom,
    locale,
    buildingInfo,
    sceneJs,
    sceneImage,
    manualChecklist,
  } = opts;
  const s = araStrings[locale];
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const marginL = 15;
  const marginR = 15;
  const contentW = pageW - marginL - marginR;
  const currentIdx = classIndexFromBuilding(buildingInfo);
  const projected = projectedClassIndex(currentIdx, bom);
  const currentClass = ENERGY_CLASSES[currentIdx];
  const projectedClass = ENERGY_CLASSES[projected.idx];
  const stats = sceneStats(sceneJs);
  const checklist = manualChecklist?.length ? manualChecklist : defaultAraChecklist(locale);
  const grandTotal = bom.reduce((sum, item) => sum + Number(item.total || 0), 0);
  let y = 0;

  const section = (title: string) => {
    if (y > pageH - 40) {
      doc.addPage();
      y = 18;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(13);
    doc.setTextColor(...C.darkText);
    doc.text(title, marginL, y);
    doc.setDrawColor(...C.amber);
    doc.setLineWidth(0.5);
    doc.line(marginL, y + 2, pageW - marginR, y + 2);
    y += 8;
  };

  const ensure = (needed: number) => {
    if (y + needed > pageH - 24) {
      doc.addPage();
      y = 18;
    }
  };

  doc.setFillColor(...C.headerBg);
  doc.rect(0, 0, pageW, 42, "F");
  doc.setFillColor(...C.amber);
  doc.rect(0, 42, pageW, 1.2, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(17);
  doc.setTextColor(...C.lightText);
  doc.text(s.header, marginL, 16);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.amberLight);
  doc.text(s.subtitle, marginL, 25);
  doc.text(fmtDate(locale), pageW - marginR, 16, { align: "right" });
  doc.setTextColor(...C.lightText);
  doc.text(projectName, marginL, 34);

  y = 53;

  section(s.building);
  const buildingLines = [
    `${s.project}: ${projectName}`,
    projectDescription ? `${strings[locale].description}: ${projectDescription}` : undefined,
    buildingInfo?.address ? `Address: ${buildingInfo.address}` : undefined,
    buildingInfo?.type ? `Type: ${buildingInfo.type}` : undefined,
    buildingInfo?.year_built ? `Built: ${buildingInfo.year_built}` : undefined,
    buildingInfo?.area_m2 ? `Area: ${buildingInfo.area_m2} m²` : undefined,
    buildingInfo?.heating ? `Heating: ${buildingInfo.heating}` : undefined,
    buildingInfo?.climate_zone ? `Climate zone: ${buildingInfo.climate_zone}` : undefined,
    buildingInfo?.heating_degree_days ? `Heating degree days: ${buildingInfo.heating_degree_days}` : undefined,
  ].filter((line): line is string => Boolean(line));

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.darkText);
  for (const line of buildingLines) {
    ensure(6);
    doc.text(line, marginL, y);
    y += 5;
  }

  y += 3;
  section(s.energy);
  const tableX = marginL;
  const tableY = y;
  const rowH = 10;
  doc.setFillColor(...C.tableHeaderBg);
  doc.rect(tableX, tableY, contentW, rowH, "F");
  doc.setTextColor(...C.lightText);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(8);
  doc.text(s.before, tableX + 4, tableY + 6.5);
  doc.text(s.after, tableX + 64, tableY + 6.5);
  doc.text(s.basis, tableX + 112, tableY + 6.5);
  doc.setFillColor(...C.rowAlt);
  doc.rect(tableX, tableY + rowH, contentW, rowH + 8, "F");
  doc.setTextColor(...C.darkText);
  doc.setFontSize(12);
  doc.text(currentClass, tableX + 8, tableY + rowH + 9);
  doc.text(projectedClass, tableX + 68, tableY + rowH + 9);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.text(projected.reasons.join(", "), tableX + 112, tableY + rowH + 6, { maxWidth: 62 });
  y += rowH * 2 + 14;

  doc.setFont("helvetica", "italic");
  doc.setFontSize(8);
  doc.setTextColor(...C.mutedText);
  doc.text(s.disclaimer, marginL, y, { maxWidth: contentW });
  y += 14;

  section(s.plan);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.darkText);
  doc.text(`${s.sceneObjects}: ${stats.objects}`, marginL, y);
  doc.text(`${s.sceneLines}: ${stats.lines}`, marginL + 55, y);
  y += 8;

  doc.setFont("helvetica", "bold");
  doc.text(s.plannedView, marginL, y);
  y += 4;
  if (sceneImage?.startsWith("data:image/")) {
    try {
      doc.addImage(sceneImage, "PNG", marginL, y, 86, 54);
    } catch {
      doc.setDrawColor(...C.tableBorder);
      doc.rect(marginL, y, 86, 54, "S");
      doc.setFont("helvetica", "normal");
      doc.setFontSize(8);
      doc.text(s.noView, marginL + 4, y + 26, { maxWidth: 78 });
    }
  } else {
    doc.setDrawColor(...C.tableBorder);
    doc.rect(marginL, y, 86, 54, "S");
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.text(s.noView, marginL + 4, y + 26, { maxWidth: 78 });
  }

  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  doc.text(s.materialSpec, marginL + 98, y + 4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  const specItems = bom.slice(0, 8);
  let specY = y + 11;
  for (const item of specItems) {
    doc.text(`• ${(item.material_name || item.material_id).substring(0, 34)} — ${item.quantity} ${item.unit}`, marginL + 98, specY, { maxWidth: 78 });
    specY += 5;
  }
  if (bom.length > specItems.length) {
    doc.text(`+ ${bom.length - specItems.length} more BOM rows`, marginL + 98, specY);
  }
  y += 64;

  section(s.attachments);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  doc.setTextColor(...C.darkText);
  for (const item of checklist) {
    ensure(7);
    doc.rect(marginL, y - 4, 3.5, 3.5, "S");
    doc.text(item, marginL + 7, y - 1);
    y += 7;
  }

  y += 4;
  section(s.cost);
  const cols = {
    material: { x: marginL, w: 92 },
    qty: { x: marginL + 92, w: 22 },
    unit: { x: marginL + 114, w: 20 },
    price: { x: marginL + 134, w: contentW - 134 },
  };
  doc.setFillColor(...C.tableHeaderBg);
  doc.rect(marginL, y, contentW, 8, "F");
  doc.setTextColor(...C.lightText);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(7);
  doc.text(s.colMaterial, cols.material.x + 2, y + 5.5);
  doc.text(s.colQty, cols.qty.x + cols.qty.w - 2, y + 5.5, { align: "right" });
  doc.text(s.colUnit, cols.unit.x + cols.unit.w - 2, y + 5.5, { align: "right" });
  doc.text(s.colPrice, cols.price.x + cols.price.w - 2, y + 5.5, { align: "right" });
  y += 8;

  bom.forEach((item, idx) => {
    ensure(7);
    if (idx % 2 === 1) {
      doc.setFillColor(...C.rowAlt);
      doc.rect(marginL, y, contentW, 7, "F");
    }
    doc.setFont("helvetica", "normal");
    doc.setFontSize(7.5);
    doc.setTextColor(...C.darkText);
    doc.text((item.material_name || item.material_id).substring(0, 46), cols.material.x + 2, y + 5);
    doc.text(String(item.quantity), cols.qty.x + cols.qty.w - 2, y + 5, { align: "right" });
    doc.text(item.unit || "kpl", cols.unit.x + cols.unit.w - 2, y + 5, { align: "right" });
    doc.setFont("helvetica", "bold");
    doc.text(`${fmtCurrency(Number(item.total || 0), locale)} EUR`, cols.price.x + cols.price.w - 2, y + 5, { align: "right" });
    y += 7;
  });

  ensure(12);
  doc.setFillColor(...C.amber);
  doc.rect(marginL, y + 3, contentW, 10, "F");
  doc.setTextColor(...C.white);
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text(s.total, marginL + 3, y + 10);
  doc.text(`${fmtCurrency(grandTotal, locale)} EUR`, pageW - marginR - 3, y + 10, { align: "right" });

  addFooter(doc, locale, pageW, pageH, marginL, marginR);
  doc.save(`helscoop_ara_${safeFilePart(projectName)}.pdf`);
}
